/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CoordinatorRouteImport } from './routes/coordinator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as CoordinatorIndexRouteImport } from './routes/coordinator.index'
import { Route as CoordinatorDonationsRouteImport } from './routes/coordinator.donations'
import { Route as CoordinatorInventoryRouteImport } from './routes/coordinator.inventory'
import { Route as CoordinatorRequestsRouteImport } from './routes/coordinator.requests'
import { Route as CoordinatorTasksRouteImport } from './routes/coordinator.tasks'
import { Route as CoordinatorTeamRouteImport } from './routes/coordinator.team'
import { Route as CoordinatorVolunteersRouteImport } from './routes/coordinator.volunteers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorRoute = CoordinatorRouteImport.update({
  id: '/coordinator',
  path: '/coordinator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorIndexRoute = CoordinatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorDonationsRoute = CoordinatorDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorInventoryRoute = CoordinatorInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorRequestsRoute = CoordinatorRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorTasksRoute = CoordinatorTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorTeamRoute = CoordinatorTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorVolunteersRoute = CoordinatorVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => CoordinatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/coordinator': typeof CoordinatorRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/coordinator/donations': typeof CoordinatorDonationsRoute
  '/coordinator/inventory': typeof CoordinatorInventoryRoute
  '/coordinator/requests': typeof CoordinatorRequestsRoute
  '/coordinator/tasks': typeof CoordinatorTasksRoute
  '/coordinator/team': typeof CoordinatorTeamRoute
  '/coordinator/volunteers': typeof CoordinatorVolunteersRoute
  '/coordinator/': typeof CoordinatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/coordinator/donations': typeof CoordinatorDonationsRoute
  '/coordinator/inventory': typeof CoordinatorInventoryRoute
  '/coordinator/requests': typeof CoordinatorRequestsRoute
  '/coordinator/tasks': typeof CoordinatorTasksRoute
  '/coordinator/team': typeof CoordinatorTeamRoute
  '/coordinator/volunteers': typeof CoordinatorVolunteersRoute
  '/coordinator': typeof CoordinatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/coordinator': typeof CoordinatorRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/coordinator/donations': typeof CoordinatorDonationsRoute
  '/coordinator/inventory': typeof CoordinatorInventoryRoute
  '/coordinator/requests': typeof CoordinatorRequestsRoute
  '/coordinator/tasks': typeof CoordinatorTasksRoute
  '/coordinator/team': typeof CoordinatorTeamRoute
  '/coordinator/volunteers': typeof CoordinatorVolunteersRoute
  '/coordinator/': typeof CoordinatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/coordinator'
    | '/login'
    | '/register'
    | '/coordinator/donations'
    | '/coordinator/inventory'
    | '/coordinator/requests'
    | '/coordinator/tasks'
    | '/coordinator/team'
    | '/coordinator/volunteers'
    | '/coordinator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/coordinator/donations'
    | '/coordinator/inventory'
    | '/coordinator/requests'
    | '/coordinator/tasks'
    | '/coordinator/team'
    | '/coordinator/volunteers'
    | '/coordinator'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/coordinator'
    | '/login'
    | '/register'
    | '/coordinator/donations'
    | '/coordinator/inventory'
    | '/coordinator/requests'
    | '/coordinator/tasks'
    | '/coordinator/team'
    | '/coordinator/volunteers'
    | '/coordinator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CoordinatorRoute: typeof CoordinatorRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator': {
      id: '/coordinator'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof CoordinatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator/': {
      id: '/coordinator/'
      path: '/'
      fullPath: '/coordinator/'
      preLoaderRoute: typeof CoordinatorIndexRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/donations': {
      id: '/coordinator/donations'
      path: '/donations'
      fullPath: '/coordinator/donations'
      preLoaderRoute: typeof CoordinatorDonationsRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/inventory': {
      id: '/coordinator/inventory'
      path: '/inventory'
      fullPath: '/coordinator/inventory'
      preLoaderRoute: typeof CoordinatorInventoryRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/requests': {
      id: '/coordinator/requests'
      path: '/requests'
      fullPath: '/coordinator/requests'
      preLoaderRoute: typeof CoordinatorRequestsRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/tasks': {
      id: '/coordinator/tasks'
      path: '/tasks'
      fullPath: '/coordinator/tasks'
      preLoaderRoute: typeof CoordinatorTasksRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/team': {
      id: '/coordinator/team'
      path: '/team'
      fullPath: '/coordinator/team'
      preLoaderRoute: typeof CoordinatorTeamRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/volunteers': {
      id: '/coordinator/volunteers'
      path: '/volunteers'
      fullPath: '/coordinator/volunteers'
      preLoaderRoute: typeof CoordinatorVolunteersRouteImport
      parentRoute: typeof CoordinatorRoute
    }
  }
}

interface CoordinatorRouteChildren {
  CoordinatorDonationsRoute: typeof CoordinatorDonationsRoute
  CoordinatorInventoryRoute: typeof CoordinatorInventoryRoute
  CoordinatorRequestsRoute: typeof CoordinatorRequestsRoute
  CoordinatorTasksRoute: typeof CoordinatorTasksRoute
  CoordinatorTeamRoute: typeof CoordinatorTeamRoute
  CoordinatorVolunteersRoute: typeof CoordinatorVolunteersRoute
  CoordinatorIndexRoute: typeof CoordinatorIndexRoute
}

const CoordinatorRouteChildren: CoordinatorRouteChildren = {
  CoordinatorDonationsRoute: CoordinatorDonationsRoute,
  CoordinatorInventoryRoute: CoordinatorInventoryRoute,
  CoordinatorRequestsRoute: CoordinatorRequestsRoute,
  CoordinatorTasksRoute: CoordinatorTasksRoute,
  CoordinatorTeamRoute: CoordinatorTeamRoute,
  CoordinatorVolunteersRoute: CoordinatorVolunteersRoute,
  CoordinatorIndexRoute: CoordinatorIndexRoute,
}

const CoordinatorRouteWithChildren = CoordinatorRoute._addFileChildren(
  CoordinatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CoordinatorRoute: CoordinatorRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
